apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluent-bit.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "fluent-bit.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fluent-bit.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "fluent-bit.name" . }}
      terminationGracePeriodSeconds: 30
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: {{ include "fluent-bit.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          env:
            - name: ELASTIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.credentialsSecret }}
                  key: api_key
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: etcmachineid
              mountPath: /etc/machine-id
              readOnly: true
            - name: fluentbit-db
              mountPath: /var/lib/fluent-bit
      volumes:
        - name: config
          configMap:
            name: {{ include "fluent-bit.name" . }}-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: etcmachineid
          hostPath:
            path: /etc/machine-id
            type: File
        - name: fluentbit-db
          hostPath:
            path: /var/lib/fluent-bit
            type: DirectoryOrCreate
